stages:
  - cleancode
  - deploy
  - unit testing

Deploy to Heroku:
  stage: deploy
  image: ruby:latest
  before_script:
    - gem install dpl
  only:
    - main
    - master
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY

test:
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  stage: unit testing
  image: node:latest
  script:
    - yarn install
    - yarn test
